# Generated by Django 4.1.5 on 2023-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='testers_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('address', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField()),
                ('testers', models.ManyToManyField(to='app.tester')),
            ],
        ),
    ]
