# Generated by Django 4.1.5 on 2023-01-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='testers',
            field=models.ManyToManyField(blank=True, to='app.tester'),
        ),
    ]
