# Generated by Django 4.1.5 on 2023-01-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_testers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tester',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='tester',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testers_photos'),
        ),
    ]
