# Generated by Django 4.1.5 on 2023-02-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_address_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='photo',
            field=models.ImageField(null=True, upload_to='testers_photos'),
        ),
    ]
